# Generated by Django 4.1.3 on 2022-12-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter natural language of the book', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
