# Generated by Django 4.1.3 on 2022-12-13 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_options_bookinstance_borrower_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['book', 'status', 'due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
