# Generated by Django 4.1.3 on 2022-12-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['book', 'status', 'due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('list_all_borrowed', 'List all books on loan'))},
        ),
    ]
