# Generated by Django 4.1.3 on 2022-12-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('update_authors', 'Add/update/delete authors from the library database'),)},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('update_books', 'Add/update/delete books from the library database'),)},
        ),
    ]
